-- Orbit CRM phase 2: operational settings, scheduling, tasks and post-sale.
-- Incremental migration: do not merge into the production foundation migration.

alter table public.organizations
  add column document text,
  add column contact_email text,
  add column phone text,
  add column website text,
  add column timezone text not null default 'America/Sao_Paulo',
  add column currency char(3) not null default 'BRL',
  add column business_hours jsonb not null default '{"1":["09:00","18:00"],"2":["09:00","18:00"],"3":["09:00","18:00"],"4":["09:00","18:00"],"5":["09:00","18:00"]}'::jsonb,
  add column booking_enabled boolean not null default false,
  add column booking_duration_minutes smallint not null default 30
    check (booking_duration_minutes between 15 and 240),
  add column booking_buffer_minutes smallint not null default 15
    check (booking_buffer_minutes between 0 and 120),
  add column meeting_location text,
  add column branding jsonb not null default '{}'::jsonb,
  add column notification_settings jsonb not null default '{}'::jsonb;

alter table public.services
  add column description text,
  add column base_price numeric(14, 2)
    check (base_price is null or base_price >= 0),
  add column meeting_duration_minutes smallint
    check (meeting_duration_minutes is null or meeting_duration_minutes between 15 and 240);

alter table public.leads
  add column archived_at timestamptz,
  add column lost_reason text,
  add column qualified_at timestamptz,
  add column ai_status text not null default 'not_analyzed'
    check (ai_status in ('not_analyzed', 'pending', 'analyzed', 'reviewed', 'failed'));

alter table public.meetings
  add column description text,
  add column location text,
  add column timezone text not null default 'America/Sao_Paulo',
  add column created_by uuid references auth.users(id) on delete set null default auth.uid(),
  add column cancellation_reason text,
  add column confirmation_status text not null default 'pending'
    check (confirmation_status in ('pending', 'confirmed', 'declined')),
  add column reminder_sent_at timestamptz,
  add column confirmed_at timestamptz,
  add column cancelled_at timestamptz,
  add unique (id, organization_id);

create table public.organization_invitations (
  id uuid primary key default gen_random_uuid(),
  organization_id uuid not null references public.organizations(id) on delete cascade,
  email text not null check (position('@' in email) > 1),
  role public.organization_role not null default 'member',
  token_hash text not null unique,
  invited_by uuid not null references auth.users(id) on delete restrict default auth.uid(),
  expires_at timestamptz not null default (now() + interval '7 days'),
  accepted_at timestamptz,
  revoked_at timestamptz,
  created_at timestamptz not null default now(),
  unique (organization_id, email, token_hash)
);

create unique index organization_invitations_pending_email_idx
  on public.organization_invitations (organization_id, lower(email))
  where accepted_at is null and revoked_at is null;

create table public.clients (
  id uuid primary key default gen_random_uuid(),
  organization_id uuid not null references public.organizations(id) on delete cascade,
  source_lead_id uuid,
  owner_id uuid,
  name text not null check (char_length(name) between 2 and 160),
  company text,
  email text,
  phone text,
  document text,
  status text not null default 'active'
    check (status in ('active', 'inactive', 'churned')),
  metadata jsonb not null default '{}'::jsonb,
  created_by uuid references auth.users(id) on delete set null default auth.uid(),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  foreign key (source_lead_id, organization_id)
    references public.leads(id, organization_id) on delete set null (source_lead_id),
  foreign key (organization_id, owner_id)
    references public.organization_members(organization_id, user_id) on delete set null (owner_id),
  unique (id, organization_id),
  unique nulls not distinct (organization_id, source_lead_id)
);

create table public.proposals (
  id uuid primary key default gen_random_uuid(),
  organization_id uuid not null references public.organizations(id) on delete cascade,
  client_id uuid,
  lead_id uuid,
  owner_id uuid,
  number bigint generated by default as identity,
  title text not null check (char_length(title) between 2 and 180),
  status text not null default 'draft'
    check (status in ('draft', 'sent', 'viewed', 'accepted', 'rejected', 'expired')),
  currency char(3) not null default 'BRL',
  subtotal numeric(14, 2) not null default 0 check (subtotal >= 0),
  discount numeric(14, 2) not null default 0 check (discount >= 0),
  total numeric(14, 2) not null default 0 check (total >= 0),
  valid_until date,
  notes text,
  sent_at timestamptz,
  accepted_at timestamptz,
  created_by uuid references auth.users(id) on delete set null default auth.uid(),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  foreign key (client_id, organization_id)
    references public.clients(id, organization_id) on delete set null (client_id),
  foreign key (lead_id, organization_id)
    references public.leads(id, organization_id) on delete set null (lead_id),
  foreign key (organization_id, owner_id)
    references public.organization_members(organization_id, user_id) on delete set null (owner_id),
  unique (id, organization_id),
  unique (organization_id, number)
);

create table public.proposal_items (
  id uuid primary key default gen_random_uuid(),
  organization_id uuid not null,
  proposal_id uuid not null,
  service_id uuid,
  description text not null check (char_length(description) between 1 and 500),
  quantity numeric(12, 2) not null default 1 check (quantity > 0),
  unit_price numeric(14, 2) not null check (unit_price >= 0),
  total numeric(14, 2) generated always as (quantity * unit_price) stored,
  position integer not null default 0 check (position >= 0),
  created_at timestamptz not null default now(),
  foreign key (proposal_id, organization_id)
    references public.proposals(id, organization_id) on delete cascade,
  foreign key (service_id, organization_id)
    references public.services(id, organization_id) on delete set null (service_id),
  unique (proposal_id, position)
);

create table public.projects (
  id uuid primary key default gen_random_uuid(),
  organization_id uuid not null references public.organizations(id) on delete cascade,
  client_id uuid not null,
  proposal_id uuid,
  owner_id uuid,
  name text not null check (char_length(name) between 2 and 180),
  status text not null default 'planned'
    check (status in ('planned', 'active', 'paused', 'completed', 'cancelled')),
  starts_on date,
  due_on date,
  completed_at timestamptz,
  metadata jsonb not null default '{}'::jsonb,
  created_by uuid references auth.users(id) on delete set null default auth.uid(),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  foreign key (client_id, organization_id)
    references public.clients(id, organization_id) on delete restrict,
  foreign key (proposal_id, organization_id)
    references public.proposals(id, organization_id) on delete set null (proposal_id),
  foreign key (organization_id, owner_id)
    references public.organization_members(organization_id, user_id) on delete set null (owner_id),
  check (due_on is null or starts_on is null or due_on >= starts_on),
  unique (id, organization_id),
  unique nulls not distinct (organization_id, proposal_id)
);

create table public.tasks (
  id uuid primary key default gen_random_uuid(),
  organization_id uuid not null references public.organizations(id) on delete cascade,
  lead_id uuid,
  client_id uuid,
  project_id uuid,
  assignee_id uuid,
  title text not null check (char_length(title) between 2 and 180),
  description text,
  status text not null default 'pending'
    check (status in ('pending', 'in_progress', 'completed', 'cancelled')),
  priority public.lead_priority not null default 'medium',
  due_at timestamptz,
  reminder_at timestamptz,
  completed_at timestamptz,
  created_by uuid references auth.users(id) on delete set null default auth.uid(),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  foreign key (lead_id, organization_id)
    references public.leads(id, organization_id) on delete cascade,
  foreign key (client_id, organization_id)
    references public.clients(id, organization_id) on delete cascade,
  foreign key (project_id, organization_id)
    references public.projects(id, organization_id) on delete cascade,
  foreign key (organization_id, assignee_id)
    references public.organization_members(organization_id, user_id) on delete set null (assignee_id),
  check (num_nonnulls(lead_id, client_id, project_id) <= 1),
  unique (id, organization_id)
);

create table public.ai_analyses (
  id uuid primary key default gen_random_uuid(),
  organization_id uuid not null,
  lead_id uuid not null,
  requested_by uuid references auth.users(id) on delete set null default auth.uid(),
  status text not null default 'pending'
    check (status in ('pending', 'completed', 'failed', 'reviewed')),
  provider text not null default 'openai',
  model text,
  prompt_version text not null,
  schema_version text not null,
  result jsonb,
  error_code text,
  input_tokens integer check (input_tokens is null or input_tokens >= 0),
  output_tokens integer check (output_tokens is null or output_tokens >= 0),
  estimated_cost_usd numeric(12, 6) check (estimated_cost_usd is null or estimated_cost_usd >= 0),
  reviewed_by uuid references auth.users(id) on delete set null,
  reviewed_at timestamptz,
  created_at timestamptz not null default now(),
  foreign key (lead_id, organization_id)
    references public.leads(id, organization_id) on delete cascade
);

create table public.integration_connections (
  id uuid primary key default gen_random_uuid(),
  organization_id uuid not null references public.organizations(id) on delete cascade,
  provider text not null check (provider in ('google_calendar', 'calendly', 'whatsapp')),
  status text not null default 'disconnected'
    check (status in ('disconnected', 'pending', 'connected', 'error', 'revoked')),
  external_account_id text,
  credentials_reference text,
  config jsonb not null default '{}'::jsonb,
  last_synced_at timestamptz,
  last_error_code text,
  created_by uuid references auth.users(id) on delete set null default auth.uid(),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (organization_id, provider),
  unique (id, organization_id)
);

create table public.conversations (
  id uuid primary key default gen_random_uuid(),
  organization_id uuid not null references public.organizations(id) on delete cascade,
  lead_id uuid,
  client_id uuid,
  provider text not null default 'whatsapp' check (provider = 'whatsapp'),
  external_contact_id text not null,
  contact_name text,
  status text not null default 'open' check (status in ('open', 'closed', 'blocked')),
  opt_in_at timestamptz,
  opt_out_at timestamptz,
  last_message_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  foreign key (lead_id, organization_id)
    references public.leads(id, organization_id) on delete set null (lead_id),
  foreign key (client_id, organization_id)
    references public.clients(id, organization_id) on delete set null (client_id),
  check (lead_id is not null or client_id is not null),
  unique (organization_id, provider, external_contact_id),
  unique (id, organization_id)
);

create table public.messages (
  id uuid primary key default gen_random_uuid(),
  organization_id uuid not null,
  conversation_id uuid not null,
  direction text not null check (direction in ('inbound', 'outbound')),
  status text not null default 'queued'
    check (status in ('queued', 'sent', 'delivered', 'read', 'received', 'failed')),
  external_id text,
  message_type text not null default 'text',
  body text,
  sent_at timestamptz,
  delivered_at timestamptz,
  read_at timestamptz,
  failed_at timestamptz,
  error_code text,
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  foreign key (conversation_id, organization_id)
    references public.conversations(id, organization_id) on delete cascade,
  unique nulls not distinct (organization_id, external_id)
);

create table private.booking_requests (
  organization_id uuid not null references public.organizations(id) on delete cascade,
  idempotency_key text not null,
  email_hash text not null,
  meeting_id uuid,
  created_at timestamptz not null default now(),
  primary key (organization_id, idempotency_key)
);

revoke all on table private.booking_requests from public, anon, authenticated;

alter table private.booking_requests
  add constraint booking_requests_meeting_fk
  foreign key (meeting_id) references public.meetings(id) on delete set null;

create index leads_active_list_idx
  on public.leads (organization_id, updated_at desc) where archived_at is null;
create index tasks_due_idx
  on public.tasks (organization_id, status, due_at) where status in ('pending', 'in_progress');
create index tasks_assignee_idx
  on public.tasks (organization_id, assignee_id, status, due_at);
create index meetings_owner_schedule_idx
  on public.meetings (organization_id, owner_id, starts_at, ends_at)
  where status = 'scheduled';
create index proposals_status_idx
  on public.proposals (organization_id, status, updated_at desc);
create index projects_status_idx
  on public.projects (organization_id, status, updated_at desc);
create index messages_timeline_idx
  on public.messages (organization_id, conversation_id, created_at desc);

create or replace function private.protect_last_owner()
returns trigger
language plpgsql
security definer
set search_path = public, pg_temp
as $$
begin
  if old.role = 'owner' and (tg_op = 'DELETE' or new.role <> 'owner') and
     (select count(*) from public.organization_members
      where organization_id = old.organization_id and role = 'owner') <= 1 then
    raise exception 'The organization must keep at least one owner';
  end if;
  return case when tg_op = 'DELETE' then old else new end;
end;
$$;

create trigger organization_members_protect_last_owner
before update of role or delete on public.organization_members
for each row execute function private.protect_last_owner();

create trigger clients_touch_updated_at before update on public.clients
for each row execute function private.touch_updated_at();
create trigger proposals_touch_updated_at before update on public.proposals
for each row execute function private.touch_updated_at();
create trigger projects_touch_updated_at before update on public.projects
for each row execute function private.touch_updated_at();
create trigger tasks_touch_updated_at before update on public.tasks
for each row execute function private.touch_updated_at();
create trigger integration_connections_touch_updated_at before update on public.integration_connections
for each row execute function private.touch_updated_at();
create trigger conversations_touch_updated_at before update on public.conversations
for each row execute function private.touch_updated_at();

create or replace function private.audit_domain_change()
returns trigger
language plpgsql
security definer
set search_path = public, pg_temp
as $$
declare
  v_row jsonb := case when tg_op = 'DELETE' then to_jsonb(old) else to_jsonb(new) end;
begin
  insert into public.audit_logs (
    organization_id, actor_user_id, entity_type, entity_id, action,
    old_values, new_values
  ) values (
    (v_row ->> 'organization_id')::uuid, auth.uid(), tg_table_name,
    (v_row ->> 'id')::uuid, lower(tg_op),
    case when tg_op in ('UPDATE', 'DELETE') then to_jsonb(old) else null end,
    case when tg_op in ('INSERT', 'UPDATE') then to_jsonb(new) else null end
  );
  return case when tg_op = 'DELETE' then old else new end;
end;
$$;

create trigger meetings_audit after insert or update or delete on public.meetings
for each row execute function private.audit_domain_change();
create trigger tasks_audit after insert or update or delete on public.tasks
for each row execute function private.audit_domain_change();
create trigger clients_audit after insert or update or delete on public.clients
for each row execute function private.audit_domain_change();
create trigger proposals_audit after insert or update or delete on public.proposals
for each row execute function private.audit_domain_change();
create trigger projects_audit after insert or update or delete on public.projects
for each row execute function private.audit_domain_change();

create or replace function public.accept_organization_invitation(p_token text)
returns uuid
language plpgsql
security definer
set search_path = public, extensions, pg_temp
as $$
declare
  v_invitation public.organization_invitations%rowtype;
  v_user_id uuid := auth.uid();
  v_email text := lower(coalesce(auth.jwt() ->> 'email', ''));
begin
  if v_user_id is null or char_length(p_token) < 32 then
    raise exception 'Invalid invitation';
  end if;

  select * into v_invitation
  from public.organization_invitations
  where token_hash = encode(digest(p_token, 'sha256'), 'hex')
    and accepted_at is null and revoked_at is null and expires_at > now()
  for update;

  if not found or lower(v_invitation.email) <> v_email then
    raise exception 'Invitation not found, expired or assigned to another email';
  end if;

  insert into public.organization_members (organization_id, user_id, role)
  values (v_invitation.organization_id, v_user_id, v_invitation.role)
  on conflict (organization_id, user_id) do nothing;

  update public.organization_invitations set accepted_at = now()
  where id = v_invitation.id;

  return v_invitation.organization_id;
end;
$$;

revoke all on function public.accept_organization_invitation(text) from public;
grant execute on function public.accept_organization_invitation(text) to authenticated;

create or replace function public.update_lead_details(
  p_organization_id uuid,
  p_lead_id uuid,
  p_name text,
  p_email text,
  p_phone text,
  p_company text,
  p_service_id uuid,
  p_owner_id uuid,
  p_source text,
  p_campaign text,
  p_estimated_budget numeric,
  p_priority public.lead_priority,
  p_score smallint,
  p_summary text,
  p_next_action text,
  p_tag_ids uuid[] default '{}'::uuid[]
)
returns void
language plpgsql
security definer
set search_path = public, pg_temp
as $$
begin
  if not private.can_write_org(p_organization_id) then raise exception 'Access denied'; end if;
  if char_length(trim(p_name)) < 2 or p_score not between 0 and 100 then
    raise exception 'Invalid lead data';
  end if;
  if p_service_id is not null and not exists (
    select 1 from public.services where id = p_service_id and organization_id = p_organization_id
  ) then raise exception 'Invalid service'; end if;
  if p_owner_id is not null and not exists (
    select 1 from public.organization_members where user_id = p_owner_id and organization_id = p_organization_id
  ) then raise exception 'Invalid owner'; end if;
  if exists (
    select 1 from unnest(p_tag_ids) tag_id
    where not exists (select 1 from public.tags where id = tag_id and organization_id = p_organization_id)
  ) then raise exception 'Invalid tag'; end if;

  update public.leads set
    name = trim(p_name), email = nullif(trim(p_email), ''), phone = nullif(trim(p_phone), ''),
    company = nullif(trim(p_company), ''), service_id = p_service_id, owner_id = p_owner_id,
    source = nullif(trim(p_source), ''), campaign = nullif(trim(p_campaign), ''),
    estimated_budget = p_estimated_budget, priority = p_priority, score = p_score,
    summary = nullif(trim(p_summary), ''), next_action = nullif(trim(p_next_action), ''),
    last_interaction_at = now()
  where id = p_lead_id and organization_id = p_organization_id;
  if not found then raise exception 'Lead not found'; end if;

  delete from public.lead_tags where lead_id = p_lead_id and organization_id = p_organization_id;
  insert into public.lead_tags (organization_id, lead_id, tag_id)
  select p_organization_id, p_lead_id, tag_id from unnest(p_tag_ids) tag_id;

  insert into public.lead_events (organization_id, lead_id, actor_user_id, event_type, metadata, source)
  values (p_organization_id, p_lead_id, auth.uid(), 'lead_updated',
    jsonb_build_object('owner_id', p_owner_id, 'priority', p_priority, 'score', p_score), 'user');
end;
$$;

revoke all on function public.update_lead_details(uuid, uuid, text, text, text, text, uuid, uuid, text, text, numeric, public.lead_priority, smallint, text, text, uuid[]) from public;
grant execute on function public.update_lead_details(uuid, uuid, text, text, text, text, uuid, uuid, text, text, numeric, public.lead_priority, smallint, text, text, uuid[]) to authenticated;

create or replace function public.set_lead_archived(
  p_organization_id uuid,
  p_lead_id uuid,
  p_archived boolean
)
returns void
language plpgsql
security definer
set search_path = public, pg_temp
as $$
begin
  if not private.can_write_org(p_organization_id) then raise exception 'Access denied'; end if;
  update public.leads set archived_at = case when p_archived then now() else null end
  where id = p_lead_id and organization_id = p_organization_id;
  if not found then raise exception 'Lead not found'; end if;
  insert into public.lead_events (organization_id, lead_id, actor_user_id, event_type, metadata, source)
  values (p_organization_id, p_lead_id, auth.uid(),
    case when p_archived then 'lead_archived' else 'lead_restored' end, '{}'::jsonb, 'user');
end;
$$;

revoke all on function public.set_lead_archived(uuid, uuid, boolean) from public;
grant execute on function public.set_lead_archived(uuid, uuid, boolean) to authenticated;

create or replace function public.get_public_booking_profile(p_slug text)
returns jsonb
language sql
stable
security definer
set search_path = public, pg_temp
as $$
  select jsonb_build_object(
    'name', name,
    'slug', slug,
    'timezone', timezone,
    'booking_duration_minutes', booking_duration_minutes,
    'business_hours', business_hours,
    'meeting_location', meeting_location
  )
  from public.organizations
  where slug = p_slug and booking_enabled = true;
$$;

revoke all on function public.get_public_booking_profile(text) from public;
grant execute on function public.get_public_booking_profile(text) to anon, authenticated;

create or replace function public.book_public_meeting(
  p_slug text,
  p_name text,
  p_email text,
  p_phone text,
  p_company text,
  p_starts_at timestamptz,
  p_idempotency_key text,
  p_website text default ''
)
returns jsonb
language plpgsql
security definer
set search_path = public, extensions, pg_temp
as $$
declare
  v_org public.organizations%rowtype;
  v_owner_id uuid;
  v_pipeline_id uuid;
  v_stage_id uuid;
  v_lead_id uuid;
  v_meeting_id uuid;
  v_ends_at timestamptz;
  v_local_start timestamp;
  v_hours jsonb;
  v_open time;
  v_close time;
  v_email_hash text;
  v_inserted integer;
begin
  if coalesce(p_website, '') <> '' then raise exception 'Invalid request'; end if;
  if char_length(trim(p_name)) not between 2 and 160 or
     char_length(trim(p_email)) > 254 or position('@' in p_email) <= 1 or
     char_length(p_idempotency_key) not between 16 and 200 or
     p_starts_at < now() + interval '30 minutes' or p_starts_at > now() + interval '90 days' then
    raise exception 'Invalid booking data';
  end if;

  select * into v_org from public.organizations
  where slug = p_slug and booking_enabled = true;
  if not found then raise exception 'Booking page not available'; end if;

  v_email_hash := encode(digest(lower(trim(p_email)), 'sha256'), 'hex');
  select meeting_id into v_meeting_id from private.booking_requests
  where organization_id = v_org.id and idempotency_key = p_idempotency_key;
  if found and v_meeting_id is not null then
    return jsonb_build_object('meeting_id', v_meeting_id, 'created', false);
  end if;
  if (select count(*) from private.booking_requests
      where organization_id = v_org.id and email_hash = v_email_hash
        and created_at > now() - interval '1 hour') >= 3 then
    raise exception 'Booking rate limit exceeded';
  end if;

  insert into private.booking_requests (organization_id, idempotency_key, email_hash)
  values (v_org.id, p_idempotency_key, v_email_hash)
  on conflict do nothing;
  get diagnostics v_inserted = row_count;
  if v_inserted = 0 then raise exception 'Booking request already processing'; end if;

  v_ends_at := p_starts_at + make_interval(mins => v_org.booking_duration_minutes);
  v_local_start := p_starts_at at time zone v_org.timezone;
  v_hours := v_org.business_hours -> extract(isodow from v_local_start)::integer::text;
  if v_hours is null or jsonb_array_length(v_hours) <> 2 then raise exception 'Outside business hours'; end if;
  v_open := (v_hours ->> 0)::time;
  v_close := (v_hours ->> 1)::time;
  if v_local_start::time < v_open or
     (v_ends_at at time zone v_org.timezone)::time > v_close then
    raise exception 'Outside business hours';
  end if;

  select user_id into v_owner_id from public.organization_members
  where organization_id = v_org.id and role <> 'viewer'
  order by case role when 'owner' then 0 when 'manager' then 1 when 'member' then 2 else 3 end,
           created_at
  limit 1;
  select id into v_pipeline_id from public.pipelines
  where organization_id = v_org.id and is_default = true;
  select id into v_stage_id from public.pipeline_stages
  where organization_id = v_org.id and pipeline_id = v_pipeline_id
  order by position limit 1;
  if v_owner_id is null or v_stage_id is null then raise exception 'Booking configuration incomplete'; end if;

  perform pg_advisory_xact_lock(hashtextextended(v_org.id::text || v_owner_id::text, 0));
  if exists (select 1 from public.meetings
    where organization_id = v_org.id and owner_id = v_owner_id and status = 'scheduled'
      and starts_at < v_ends_at + make_interval(mins => v_org.booking_buffer_minutes)
      and ends_at + make_interval(mins => v_org.booking_buffer_minutes) > p_starts_at
  ) then raise exception 'Meeting time is no longer available'; end if;

  insert into public.leads (
    organization_id, pipeline_id, stage_id, owner_id, name, email, phone,
    company, source, priority, custom_fields, created_by
  ) values (
    v_org.id, v_pipeline_id, v_stage_id, v_owner_id, trim(p_name), lower(trim(p_email)),
    nullif(trim(p_phone), ''), nullif(trim(p_company), ''), 'public_booking',
    'medium', '{}'::jsonb, null
  ) returning id into v_lead_id;

  insert into public.meetings (
    organization_id, lead_id, owner_id, title, starts_at, ends_at, location,
    timezone, external_provider, external_id, created_by
  ) values (
    v_org.id, v_lead_id, v_owner_id, 'Reunião com ' || trim(p_name),
    p_starts_at, v_ends_at, v_org.meeting_location, v_org.timezone,
    'public_booking', p_idempotency_key, null
  ) returning id into v_meeting_id;

  insert into public.lead_events (
    organization_id, lead_id, actor_user_id, event_type, metadata, source,
    idempotency_key
  ) values (
    v_org.id, v_lead_id, null, 'meeting_scheduled',
    jsonb_build_object('meeting_id', v_meeting_id, 'starts_at', p_starts_at),
    'automation', 'public_booking:' || p_idempotency_key
  );
  update private.booking_requests set meeting_id = v_meeting_id
  where organization_id = v_org.id and idempotency_key = p_idempotency_key;

  return jsonb_build_object('meeting_id', v_meeting_id, 'created', true);
end;
$$;

revoke all on function public.book_public_meeting(text, text, text, text, text, timestamptz, text, text) from public;
grant execute on function public.book_public_meeting(text, text, text, text, text, timestamptz, text, text) to anon, authenticated;

create or replace function public.healthcheck()
returns jsonb
language sql
stable
security invoker
set search_path = public, pg_temp
as $$ select jsonb_build_object('database', 'ok', 'checked_at', now()) $$;

revoke all on function public.healthcheck() from public;
grant execute on function public.healthcheck() to anon, authenticated;

create or replace function public.get_operational_metrics(p_organization_id uuid)
returns jsonb
language sql
stable
security definer
set search_path = public, pg_temp
as $$
  select case when private.is_org_member(p_organization_id) then jsonb_build_object(
    'upcoming_meetings', (select count(*) from public.meetings where organization_id = p_organization_id and status = 'scheduled' and starts_at between now() and now() + interval '7 days'),
    'open_tasks', (select count(*) from public.tasks where organization_id = p_organization_id and status in ('pending', 'in_progress')),
    'overdue_tasks', (select count(*) from public.tasks where organization_id = p_organization_id and status in ('pending', 'in_progress') and due_at < now()),
    'active_clients', (select count(*) from public.clients where organization_id = p_organization_id and status = 'active'),
    'active_projects', (select count(*) from public.projects where organization_id = p_organization_id and status in ('planned', 'active', 'paused')),
    'seller_performance', coalesce((
      select jsonb_agg(jsonb_build_object(
        'user_id', om.user_id,
        'name', coalesce(pr.full_name, 'Membro'),
        'leads', coalesce(t.leads, 0),
        'won', coalesce(t.won, 0),
        'pipeline_value', coalesce(t.pipeline_value, 0)
      ) order by coalesce(t.won, 0) desc, coalesce(t.pipeline_value, 0) desc)
      from public.organization_members om
      left join public.profiles pr on pr.id = om.user_id
      left join (
        select l.owner_id, count(*) leads,
          count(*) filter (where ps.is_won) won,
          coalesce(sum(l.estimated_budget) filter (where not ps.is_closed), 0) pipeline_value
        from public.leads l join public.pipeline_stages ps on ps.id = l.stage_id
        where l.organization_id = p_organization_id and l.archived_at is null
        group by l.owner_id
      ) t on t.owner_id = om.user_id
      where om.organization_id = p_organization_id
    ), '[]'::jsonb)
  ) else null end;
$$;

revoke all on function public.get_operational_metrics(uuid) from public;
grant execute on function public.get_operational_metrics(uuid) to authenticated;

create or replace function private.audit_lead_deleted()
returns trigger
language plpgsql
security definer
set search_path = public, pg_temp
as $$
begin
  insert into public.audit_logs (organization_id, actor_user_id, entity_type, entity_id, action, old_values)
  values (old.organization_id, auth.uid(), 'lead', old.id, 'deleted', to_jsonb(old));
  return old;
end;
$$;

create trigger leads_audit_delete before delete on public.leads
for each row execute function private.audit_lead_deleted();

create or replace function public.schedule_meeting(
  p_organization_id uuid,
  p_lead_id uuid,
  p_owner_id uuid,
  p_title text,
  p_starts_at timestamptz,
  p_ends_at timestamptz,
  p_timezone text,
  p_description text default null,
  p_location text default null
)
returns uuid
language plpgsql
security definer
set search_path = public, pg_temp
as $$
declare
  v_meeting_id uuid;
begin
  if not private.can_write_org(p_organization_id) then
    raise exception 'Access denied';
  end if;
  if p_ends_at <= p_starts_at or p_starts_at < now() - interval '5 minutes' then
    raise exception 'Invalid meeting period';
  end if;
  if not exists (select 1 from public.leads where id = p_lead_id and organization_id = p_organization_id) or
     not exists (select 1 from public.organization_members where organization_id = p_organization_id and user_id = p_owner_id) then
    raise exception 'Lead or owner does not belong to the organization';
  end if;

  perform pg_advisory_xact_lock(hashtextextended(p_organization_id::text || p_owner_id::text, 0));
  if exists (
    select 1 from public.meetings
    where organization_id = p_organization_id and owner_id = p_owner_id
      and status = 'scheduled' and starts_at < p_ends_at and ends_at > p_starts_at
  ) then
    raise exception 'Meeting time conflicts with another appointment';
  end if;

  insert into public.meetings (
    organization_id, lead_id, owner_id, title, starts_at, ends_at,
    timezone, description, location, created_by
  ) values (
    p_organization_id, p_lead_id, p_owner_id, trim(p_title), p_starts_at,
    p_ends_at, p_timezone, nullif(trim(p_description), ''),
    nullif(trim(p_location), ''), auth.uid()
  ) returning id into v_meeting_id;

  insert into public.lead_events (
    organization_id, lead_id, actor_user_id, event_type, metadata, source
  ) values (
    p_organization_id, p_lead_id, auth.uid(), 'meeting_scheduled',
    jsonb_build_object('meeting_id', v_meeting_id, 'starts_at', p_starts_at), 'user'
  );

  return v_meeting_id;
end;
$$;

revoke all on function public.schedule_meeting(uuid, uuid, uuid, text, timestamptz, timestamptz, text, text, text) from public;
grant execute on function public.schedule_meeting(uuid, uuid, uuid, text, timestamptz, timestamptz, text, text, text) to authenticated;

create or replace function public.update_meeting_status(
  p_organization_id uuid,
  p_meeting_id uuid,
  p_status text,
  p_reason text default null
)
returns void
language plpgsql
security definer
set search_path = public, pg_temp
as $$
declare
  v_meeting public.meetings%rowtype;
begin
  if not private.can_write_org(p_organization_id) or
     p_status not in ('scheduled', 'cancelled', 'completed', 'no_show') then
    raise exception 'Access denied or invalid status';
  end if;
  select * into v_meeting from public.meetings
  where id = p_meeting_id and organization_id = p_organization_id for update;
  if not found then raise exception 'Meeting not found'; end if;

  update public.meetings set
    status = p_status,
    cancellation_reason = case when p_status = 'cancelled' then nullif(trim(p_reason), '') else cancellation_reason end,
    cancelled_at = case when p_status = 'cancelled' then now() else null end
  where id = v_meeting.id;

  insert into public.lead_events (
    organization_id, lead_id, actor_user_id, event_type, metadata, source
  ) values (
    p_organization_id, v_meeting.lead_id, auth.uid(),
    case p_status when 'cancelled' then 'meeting_cancelled'
                  when 'completed' then 'meeting_completed'
                  when 'no_show' then 'meeting_no_show'
                  else 'meeting_rescheduled' end,
    jsonb_build_object('meeting_id', v_meeting.id, 'reason', nullif(trim(p_reason), '')),
    'user'
  );
end;
$$;

revoke all on function public.update_meeting_status(uuid, uuid, text, text) from public;
grant execute on function public.update_meeting_status(uuid, uuid, text, text) to authenticated;

create or replace function public.convert_won_lead(
  p_organization_id uuid,
  p_lead_id uuid,
  p_project_name text
)
returns jsonb
language plpgsql
security definer
set search_path = public, pg_temp
as $$
declare
  v_lead public.leads%rowtype;
  v_stage public.pipeline_stages%rowtype;
  v_client_id uuid;
  v_project_id uuid;
  v_existing jsonb;
begin
  if not private.can_write_org(p_organization_id) then raise exception 'Access denied'; end if;
  select * into v_lead from public.leads
    where id = p_lead_id and organization_id = p_organization_id for update;
  if not found then raise exception 'Lead not found'; end if;
  select metadata into v_existing from public.lead_events
  where organization_id = p_organization_id and source = 'user'
    and idempotency_key = 'deal_won:' || v_lead.id::text;
  if found then return v_existing; end if;
  select * into v_stage from public.pipeline_stages where id = v_lead.stage_id;
  if not v_stage.is_won then raise exception 'Lead is not in a won stage'; end if;

  insert into public.clients (
    organization_id, source_lead_id, owner_id, name, company, email, phone, created_by
  ) values (
    p_organization_id, v_lead.id, v_lead.owner_id, v_lead.name,
    v_lead.company, v_lead.email, v_lead.phone, auth.uid()
  ) on conflict (organization_id, source_lead_id) do update set updated_at = now()
  returning id into v_client_id;

  insert into public.projects (
    organization_id, client_id, owner_id, name, status, created_by
  ) values (
    p_organization_id, v_client_id, v_lead.owner_id, trim(p_project_name), 'planned', auth.uid()
  ) returning id into v_project_id;

  insert into public.lead_events (
    organization_id, lead_id, actor_user_id, event_type, metadata, source,
    idempotency_key
  ) values (
    p_organization_id, v_lead.id, auth.uid(), 'deal_won',
    jsonb_build_object('client_id', v_client_id, 'project_id', v_project_id),
    'user', 'deal_won:' || v_lead.id::text
  ) on conflict (organization_id, source, idempotency_key) where idempotency_key is not null do nothing;

  return jsonb_build_object('client_id', v_client_id, 'project_id', v_project_id);
end;
$$;

revoke all on function public.convert_won_lead(uuid, uuid, text) from public;
grant execute on function public.convert_won_lead(uuid, uuid, text) to authenticated;

alter table public.organization_invitations enable row level security;
alter table public.clients enable row level security;
alter table public.proposals enable row level security;
alter table public.proposal_items enable row level security;
alter table public.projects enable row level security;
alter table public.tasks enable row level security;
alter table public.ai_analyses enable row level security;
alter table public.integration_connections enable row level security;
alter table public.conversations enable row level security;
alter table public.messages enable row level security;

create policy invitations_select_admin on public.organization_invitations for select
to authenticated using (private.is_org_admin(organization_id));
create policy invitations_insert_admin on public.organization_invitations for insert
to authenticated with check (private.is_org_admin(organization_id) and invited_by = auth.uid());
create policy invitations_update_admin on public.organization_invitations for update
to authenticated using (private.is_org_admin(organization_id)) with check (private.is_org_admin(organization_id));
create policy invitations_delete_admin on public.organization_invitations for delete
to authenticated using (private.is_org_admin(organization_id));

create policy clients_select_member on public.clients for select
to authenticated using (private.is_org_member(organization_id));
create policy clients_write_member on public.clients for all
to authenticated using (private.can_write_org(organization_id)) with check (private.can_write_org(organization_id));
create policy proposals_select_member on public.proposals for select
to authenticated using (private.is_org_member(organization_id));
create policy proposals_write_member on public.proposals for all
to authenticated using (private.can_write_org(organization_id)) with check (private.can_write_org(organization_id));
create policy proposal_items_select_member on public.proposal_items for select
to authenticated using (private.is_org_member(organization_id));
create policy proposal_items_write_member on public.proposal_items for all
to authenticated using (private.can_write_org(organization_id)) with check (private.can_write_org(organization_id));
create policy projects_select_member on public.projects for select
to authenticated using (private.is_org_member(organization_id));
create policy projects_write_member on public.projects for all
to authenticated using (private.can_write_org(organization_id)) with check (private.can_write_org(organization_id));
create policy tasks_select_member on public.tasks for select
to authenticated using (private.is_org_member(organization_id));
create policy tasks_write_member on public.tasks for all
to authenticated using (private.can_write_org(organization_id)) with check (private.can_write_org(organization_id));
create policy ai_analyses_select_member on public.ai_analyses for select
to authenticated using (private.is_org_member(organization_id));
create policy ai_analyses_insert_member on public.ai_analyses for insert
to authenticated with check (private.can_write_org(organization_id) and requested_by = auth.uid());
create policy ai_analyses_update_admin on public.ai_analyses for update
to authenticated using (private.is_org_admin(organization_id)) with check (private.is_org_admin(organization_id));
create policy integration_connections_select_admin on public.integration_connections for select
to authenticated using (private.is_org_admin(organization_id));
create policy integration_connections_write_admin on public.integration_connections for all
to authenticated using (private.is_org_admin(organization_id)) with check (private.is_org_admin(organization_id));
create policy conversations_select_member on public.conversations for select
to authenticated using (private.is_org_member(organization_id));
create policy conversations_write_member on public.conversations for all
to authenticated using (private.can_write_org(organization_id)) with check (private.can_write_org(organization_id));
create policy messages_select_member on public.messages for select
to authenticated using (private.is_org_member(organization_id));
-- Message writes are intentionally reserved for trusted provider workers.

revoke all on table public.organization_invitations, public.clients,
  public.proposals, public.proposal_items, public.projects, public.tasks,
  public.ai_analyses, public.integration_connections, public.conversations,
  public.messages from anon;

grant select, insert, update, delete on public.organization_invitations to authenticated;
grant select, insert, update, delete on public.clients to authenticated;
grant select, insert, update, delete on public.proposals to authenticated;
grant select, insert, update, delete on public.proposal_items to authenticated;
grant select, insert, update, delete on public.projects to authenticated;
grant select, insert, update, delete on public.tasks to authenticated;
grant select, insert, update on public.ai_analyses to authenticated;
grant select, insert, update, delete on public.integration_connections to authenticated;
grant select, insert, update, delete on public.conversations to authenticated;
grant select on public.messages to authenticated;

revoke execute on function private.protect_last_owner() from public, anon, authenticated;
revoke execute on function private.audit_lead_deleted() from public, anon, authenticated;
revoke execute on function private.audit_domain_change() from public, anon, authenticated;

comment on table public.integration_connections is
  'Provider state and non-sensitive config. credentials_reference points to a server-only secret store; tokens never belong in config.';
comment on function public.schedule_meeting(uuid, uuid, uuid, text, timestamptz, timestamptz, text, text, text) is
  'Schedules a meeting with tenant validation, serialized conflict detection and a lead event.';
comment on function public.convert_won_lead(uuid, uuid, text) is
  'Creates the client and initial project from a won lead and records the deal_won fact.';
comment on function public.book_public_meeting(text, text, text, text, text, timestamptz, text, text) is
  'Public idempotent booking boundary with honeypot, per-email throttling, availability and conflict checks.';
